env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: 
  no-async-promise-executor: error
  no-await-in-loop: error
  no-promise-executor-return: error
  require-atomic-updates: error
  max-nested-callbacks: [error, 5]
  no-return-await: error
  prefer-promise-reject-errors: error
